ignore:
#  Mini Model <minimodel@metamodel.me>

exclude:
  languages

mapping:
  "Christopher Boelter <christopher@boelter.eu>":
    - "cogizz <c.boelter@cogizz.de>"
    - "cboelter <christopher@boelter.eu>"
    - "Christopher Boelter <c.boelter@cogizz.de>"
